# Generated by Codex on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_merge_20260209_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='citations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
