# Generated by ChatGPT on 2026-01-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_chats_session_user_idx_chats_chats_user_id_987f9c_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='model_id',
            new_name='model',
        ),
    ]
