# Generated by ChatGPT on 2026-01-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_artifact_job_kind_idx_jobs_artifa_job_id_e21ea2_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='model_id',
            new_name='model',
        ),
    ]
