# Generated by ChatGPT on 2026-01-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_membersh_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='membership_status',
        ),
    ]
